# Use something that's not 'ruby' so we don't set up things like
# RVM/bundler/ruby and whatnot. Right now 'rust' isn't a language on travis and
# it treats unknown languages as ruby-like I believe.
language: c

os:
- linux
- osx

# Before we start doing anything, install a stock LLVM
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  ./travis.linux.install.deps.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./travis.osx.install.deps.sh; fi

# All of the llvm tools are suffixed with "-$VERS" which we don't want, so
# symlink them all into a local directory and just use that
#
# FIXME: this shouldn't update the src/llvm sub-repo, that takes about a minute
#        it's gotta download so much stuff.
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  ./travis.linux.before_script.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./travis.osx.before_script.sh; fi
  - export NO_BENCH=1
  - export RUST_SHA=`git rev-parse HEAD^`

script:
  - travis_wait make -j4 rustc-stage1
  - travis_wait make -j4 rustc-stage2
  - make -j4 dist

env: LLVM_VERSION=3.5

# We track this ourselves, and in theory we don't have to update the LLVM repo
# (but sadly we do right now anyway).
git:
  submodules: false

notifications:
  email: false

branches:
  only:
  - travis

after_success:
- ls
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ls x86_64-unknown-linux-gnu; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ls x86_64-apple-darwin; fi
- ls dist

deploy:
  provider: s3
  access_key_id: AKIAIN2TFNMLB7CJFXDA
  secret_access_key:
    secure: VKmt9KkBSu9uq05hffhZtLGw/vJ8DYVQsl6z92HZzNjT2g3H3OFoIOVG9i7TVzZJxDbA/cIsV5E3WoQvamMmuSNli0rZMzx9RXJK249O0UlFe3FDMEt86REyEy2Rwz8MhSnW0Vfygs+HvUFADCHA9n8ySKnl2CYG7qdpnDtZ1Xs=
  bucket: servo-rust
  local-dir: dist
  skip_cleanup: true
  upload-dir: $RUST_SHA
  on:
    branch: travis
